language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
    - node_modules
branches:
  only:
  - master
  - gh-pages
before_install:
  - npm install -g coveralls
script:
  # - npm test -- --coverage && cat ./coverage/lcov.info | coveralls
  - npm test -- --coverage