a = Area.new({name: "Utah", year_established: nil, parent_id: nil})
a.save(validate:false)
Area.create!([
  {name: "Wasatch Range", year_established: nil, parent_id: 1},
  {name: "Lone Peak Cirque", year_established: nil, parent_id: 2},
  {name: "Question Mark Wall", year_established: nil, parent_id: 3},
  {name: "Maple Canyon", year_established: nil, parent_id: 1},
  {name: "Maple Canyon Road", year_established: nil, parent_id: 5},
  {name: "Heart Rock Area", year_established: nil, parent_id: 6},
  {name: "Heart Rock", year_established: nil, parent_id: 7},
  {name: "Bell's Canyon", year_established: nil, parent_id: 2},
  {name: "Middle Bell Tower", year_established: nil, parent_id: 9},
  {name: "Little Cottonwood Canyon", year_established: nil, parent_id: 2},
  {name: "Coffin Buttress", year_established: nil, parent_id: 11},
  {name: "The Thumb Area", year_established: nil, parent_id: 11},
  {name: "Summit Wall", year_established: nil, parent_id: 3},
  {name: "Pentapitch Area", year_established: nil, parent_id: 11},
  {name: "Big Cottonwood Canyon", year_established: nil, parent_id: 2},
  {name: "Storm Mountain Picnic Area", year_established: nil, parent_id: 16},
  {name: "Storm Mountain Island", year_established: nil, parent_id: 17},
  {name: "Crescent Crack Buttress", year_established: nil, parent_id: 11},
  {name: "Bongeater Buttress", year_established: nil, parent_id: 11},
  {name: "American Fork Canyon", year_established: nil, parent_id: 2},
  {name: "The Membrane", year_established: nil, parent_id: 21},
  {name: "Gate Buttress", year_established: nil, parent_id: 11},
  {name: "Dihedrals Area", year_established: nil, parent_id: 23},
  {name: "South Summit Wall", year_established: nil, parent_id: 3},
  {name: "Green Adjective Gully", year_established: nil, parent_id: 11},
  {name: "Mount Olympus", year_established: nil, parent_id: 2},
  {name: "The West Slabs", year_established: nil, parent_id: 27},
  {name: "The Dead Snag", year_established: nil, parent_id: 16},
  {name: "Hard Rock", year_established: nil, parent_id: 21},
  {name: "Glass Ocean and Environs", year_established: nil, parent_id: 16},
  {name: "JHCOB Wall", year_established: nil, parent_id: 16},
  {name: "Waterfront, The", year_established: nil, parent_id: 11},
  {name: "Ferguson Canyon", year_established: nil, parent_id: 2},
  {name: "The Watchtower", year_established: nil, parent_id: 34},
  {name: "Watchtower Main", year_established: nil, parent_id: 35},
  {name: "Beckey's Wall Area", year_established: nil, parent_id: 23},
  {name: "S-Curves", year_established: nil, parent_id: 16},
  {name: "S-Curve - Lower", year_established: nil, parent_id: 38},
  {name: "Coal Pit Buttress", year_established: nil, parent_id: 11},
  {name: "White Wave Wall", year_established: nil, parent_id: 21},
  {name: "Division Wall", year_established: nil, parent_id: 21},
  {name: "Wheeler-Newsome Wall", year_established: nil, parent_id: 11},
  {name: "Sundial", year_established: nil, parent_id: 16},
  {name: "Lizard Head Wall", year_established: nil, parent_id: 11},
  {name: "Challenge Buttress", year_established: nil, parent_id: 16},
  {name: "North and West Faces", year_established: nil, parent_id: 46},
  {name: "Schoolroom Area", year_established: nil, parent_id: 23},
  {name: "Plumb Line Gully", year_established: nil, parent_id: 11},
  {name: "Albion Basin", year_established: nil, parent_id: 11},
  {name: "Devil's Castle", year_established: nil, parent_id: 50},
  {name: "Serenity", year_established: nil, parent_id: 21},
  {name: "Eavesdown Docks", year_established: nil, parent_id: 52},
  {name: "Hellgate Cliffs", year_established: nil, parent_id: 11},
  {name: "Tower One", year_established: nil, parent_id: 54},
  {name: "Echo Canyon", year_established: nil, parent_id: 1},
  {name: "The Dry Wall", year_established: nil, parent_id: 56},
  {name: "Watchtower Tiers", year_established: nil, parent_id: 35},
  {name: "S-Curve - The Pile", year_established: nil, parent_id: 38},
  {name: "Escape Buttress", year_established: nil, parent_id: 21},
  {name: "Narcolepsy Area", year_established: nil, parent_id: 16},
  {name: "Kermits Wall", year_established: nil, parent_id: 11},
  {name: "Battalion of Saints Wall", year_established: nil, parent_id: 16},
  {name: "The Egg", year_established: nil, parent_id: 11},
  {name: "East Hellgate", year_established: nil, parent_id: 54},
  {name: "The Melting Mud Wall", year_established: nil, parent_id: 65},
  {name: "East Face", year_established: nil, parent_id: 46},
  {name: "Salt Lake Slips", year_established: nil, parent_id: 16},
  {name: "Bumble Bee Wall", year_established: nil, parent_id: 17},
  {name: "Parley's Canyon", year_established: nil, parent_id: 2},
  {name: "Iron Curtain Wall", year_established: nil, parent_id: 70},
  {name: "Ambush Wall", year_established: nil, parent_id: 16},
  {name: "Bingo Baby", year_established: nil, parent_id: 21},
  {name: "Little Mill Area", year_established: nil, parent_id: 21},
  {name: "The Fin", year_established: nil, parent_id: 11},
  {name: "Tanners Gulch", year_established: nil, parent_id: 11},
  {name: "Minions of Chaos Area", year_established: nil, parent_id: 76},
  {name: "Mule Hollow Wall", year_established: nil, parent_id: 16},
  {name: "Dam Wall", year_established: nil, parent_id: 17},
  {name: "Dogwood Crag", year_established: nil, parent_id: 16},
  {name: "Reservoir Ridge", year_established: nil, parent_id: 17},
  {name: "Psychobabble Wall", year_established: nil, parent_id: 17},
  {name: "Dragon Arch", year_established: nil, parent_id: 11},
  {name: "The Sail", year_established: nil, parent_id: 11},
  {name: "Coalpit Gulch", year_established: nil, parent_id: 11},
  {name: "Industrial Wall", year_established: nil, parent_id: 85},
  {name: "East Gate Buttress", year_established: nil, parent_id: 23},
  {name: "Penitentiary Wall", year_established: nil, parent_id: 16},
  {name: "Altered States Gully", year_established: nil, parent_id: 11},
  {name: "Red Rock", year_established: nil, parent_id: 2},
  {name: "The Red Rock", year_established: nil, parent_id: 90},
  {name: "S-Curve - Upper Wall", year_established: nil, parent_id: 38},
  {name: "The Billboard Trail", year_established: nil, parent_id: 21},
  {name: "The Billboard", year_established: nil, parent_id: 93},
  {name: "Black Magic", year_established: nil, parent_id: 21},
  {name: "The Cathedral", year_established: nil, parent_id: 34},
  {name: "Upper Division Wall", year_established: nil, parent_id: 21},
  {name: "The Millstone", year_established: nil, parent_id: 16},
  {name: "Tower Of Babel", year_established: nil, parent_id: 34},
  {name: "The Burnt Wall", year_established: nil, parent_id: 16},
  {name: "Tower Two", year_established: nil, parent_id: 54},
  {name: "Melting Mud West", year_established: nil, parent_id: 65},
  {name: "Hell Area", year_established: nil, parent_id: 21},
  {name: "Hell Wall", year_established: nil, parent_id: 103},
  {name: "Cecret Lake", year_established: nil, parent_id: 50},
  {name: "Creekside Wall", year_established: nil, parent_id: 105},
  {name: "Moab Area", year_established: nil, parent_id: 1},
  {name: "Potash Road", year_established: nil, parent_id: 107},
  {name: "Wall Street", year_established: nil, parent_id: 108},
  {name: "Rock Canyon", year_established: nil, parent_id: 2},
  {name: "Treasure Island", year_established: nil, parent_id: 110},
  {name: "Lisa Falls", year_established: nil, parent_id: 11},
  {name: "Lisa Falls Buttress", year_established: nil, parent_id: 112},
  {name: "Choss Garden", year_established: nil, parent_id: 16},
  {name: "Strone Crag", year_established: nil, parent_id: 16},
  {name: "South Summit", year_established: nil, parent_id: 27},
  {name: "Beer Can Alley", year_established: nil, parent_id: 21},
  {name: "Cannabis Wall", year_established: nil, parent_id: 21},
  {name: "Hyperform Wall", year_established: nil, parent_id: 3},
  {name: "Waterfall Wall", year_established: nil, parent_id: 85},
  {name: "Ogden", year_established: nil, parent_id: 2},
  {name: "Ogden Canyon", year_established: nil, parent_id: 121},
  {name: "Utah Wall", year_established: nil, parent_id: 122},
  {name: "Broads Fork", year_established: nil, parent_id: 16},
  {name: "Goldenfingers Wall", year_established: nil, parent_id: 34},
  {name: "Green Stash Wall", year_established: nil, parent_id: 105},
  {name: "Goat Gully Wall", year_established: nil, parent_id: 65},
  {name: "Static Wall", year_established: nil, parent_id: 17},
  {name: "Gargoyle Wall", year_established: nil, parent_id: 11},
  {name: "Maybird Slide Area", year_established: nil, parent_id: 11},
  {name: "Purple Wall", year_established: nil, parent_id: 130},
  {name: "The Blue Walls", year_established: nil, parent_id: 21},
  {name: "Red Rock Wall", year_established: nil, parent_id: 16},
  {name: "Geezer Wall", year_established: nil, parent_id: 16},
  {name: "Main Slab", year_established: nil, parent_id: 134},
  {name: "Lonely Challenge Area", year_established: nil, parent_id: 16},
  {name: "Nuts and Bolts", year_established: nil, parent_id: 122},
  {name: "Burner Buttress", year_established: nil, parent_id: 11},
  {name: "Hole in the Rock", year_established: nil, parent_id: 122},
  {name: "Specter Wall", year_established: nil, parent_id: 76},
  {name: "Persephone", year_established: nil, parent_id: 52},
  {name: "Goatland Wall", year_established: nil, parent_id: 65},
  {name: "Great White Icicle Area", year_established: nil, parent_id: 11},
  {name: "The Schoolroom", year_established: nil, parent_id: 121},
  {name: "Ramp Routes", year_established: nil, parent_id: 144},
  {name: "El Diablo Wall", year_established: nil, parent_id: 103},
  {name: "Main Hellgate", year_established: nil, parent_id: 54},
  {name: "Grey Cliffs Picnic Area", year_established: nil, parent_id: 21},
  {name: "The Grey Cliffs", year_established: nil, parent_id: 148},
  {name: "North Summit", year_established: nil, parent_id: 27},
  {name: "Dark Star Gully", year_established: nil, parent_id: 16},
  {name: "Big Willow Canyon", year_established: nil, parent_id: 2},
  {name: "Twilight Buttress", year_established: nil, parent_id: 152},
  {name: "Whipper Wall", year_established: nil, parent_id: 105},
  {name: "9th Street", year_established: nil, parent_id: 121},
  {name: "Black Peeler Buttress", year_established: nil, parent_id: 11},
  {name: "South Face", year_established: nil, parent_id: 156},
  {name: "The Bungalow", year_established: nil, parent_id: 70},
  {name: "Hell Cave", year_established: nil, parent_id: 103},
  {name: "Brighton's Frighton Wall", year_established: nil, parent_id: 16},
  {name: "Hogum Fork", year_established: nil, parent_id: 11},
  {name: "The Red Corners", year_established: nil, parent_id: 21},
  {name: "Book of Condolences", year_established: nil, parent_id: 162},
  {name: "Aguaworld", year_established: nil, parent_id: 16},
  {name: "Wasatch Alpine Areas", year_established: nil, parent_id: 2},
  {name: "Pfeifferhorn", year_established: nil, parent_id: 165},
  {name: "Allen's Ridge Area", year_established: nil, parent_id: 11},
  {name: "Intensive Care Slab", year_established: nil, parent_id: 11},
  {name: "West Desert", year_established: nil, parent_id: 1},
  {name: "Stansbury Mountains", year_established: nil, parent_id: 169},
  {name: "South Willow Canyon - Narrows", year_established: nil, parent_id: 170},
  {name: "Narrows - South", year_established: nil, parent_id: 171},
  {name: "Aqueduct Area, The", year_established: nil, parent_id: 16},
  {name: "Roadside Crag", year_established: nil, parent_id: 56},
  {name: "Booty Wall Area", year_established: nil, parent_id: 76},
  {name: "Neff's Canyon", year_established: nil, parent_id: 2},
  {name: "Chadbourne Crag", year_established: nil, parent_id: 176},
  {name: "West Bell Tower", year_established: nil, parent_id: 9},
  {name: "Riptide Wall", year_established: nil, parent_id: 70},
  {name: "Haven", year_established: nil, parent_id: 52}
])
ClimbingRoute.create!([
  {name: "Lowe Route", area_id: 4, protection_type: "Trad, Alpine", pitches: 3, picture: nil},
  {name: "Tachycardia", area_id: 8, protection_type: "Sport", pitches: 3, picture: nil},
  {name: "Arm and Hammer", area_id: 10, protection_type: "Trad", pitches: 6, picture: nil},
  {name: "The Coffin", area_id: 12, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "S-Direct", area_id: 13, protection_type: "Trad", pitches: 7, picture: nil},
  {name: "Triple Overhangs", area_id: 14, protection_type: "Trad, Alpine", pitches: 4, picture: nil},
  {name: "Sasquatch", area_id: 15, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Goodro's Wall", area_id: 18, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Mexican Crack", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Bongeater", area_id: 20, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "License To Thrill", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Equipment Overhang", area_id: 24, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Center Thumb", area_id: 25, protection_type: "Trad, Alpine", pitches: 5, picture: nil},
  {name: "Gordon's Hangover", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Pentapitch", area_id: 15, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "The Green Adjective", area_id: 26, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Satan's Corner", area_id: 24, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "The West Slabs", area_id: 28, protection_type: "Trad", pitches: 10, picture: nil},
  {name: "Steorts' Ridge", area_id: 29, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Winds of Fire", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "All Chalk And No Action", area_id: 26, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "High Dive", area_id: 31, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Outside Corner", area_id: 32, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "After The Fall", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Disco Duck", area_id: 33, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Extreme Unction", area_id: 36, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Beckey's Wall", area_id: 37, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Half-A-Finger", area_id: 24, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Black Monday", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stiffler's Mom", area_id: 40, protection_type: "Trad", pitches: 12, picture: nil},
  {name: "Naked Nebula", area_id: 41, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Black and White John and Mary", area_id: 24, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Gordon's Direct", area_id: 26, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Division", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Wheels on Fire", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Tick Fever", area_id: 43, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "The Viewing", area_id: 12, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Teeanova", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Eleventh Hour", area_id: 44, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Wheels on Fire Direct", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Isotoner Moaner", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Liquid Oxygen", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Squeeze My Lemon", area_id: 45, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Better than Bitter", area_id: 47, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bushwhack Crack", area_id: 48, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Plumb Line", area_id: 49, protection_type: "Trad, TR", pitches: 0, picture: nil},
  {name: "Black Streak", area_id: 51, protection_type: "Trad, Alpine", pitches: 7, picture: nil},
  {name: "Out of Gas", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Final Link", area_id: 19, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Medussa", area_id: 55, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pocket Full of Trundles", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Glass Ocean", area_id: 31, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Suicide Blonde", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Schoolroom", area_id: 48, protection_type: "Trad", pitches: 5, picture: nil},
  {name: "Uncensored Society", area_id: 58, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Touch Up", area_id: 26, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Right Pile", area_id: 59, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Jig's Up", area_id: 29, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Hollow Man", area_id: 47, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Crescent Crack", area_id: 19, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Tingey's Torture", area_id: 37, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Monkey Meet", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Platinum Blonde", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Litmus Test", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dream Slate", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Tingey's Terror", area_id: 37, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Juggernaut", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Something Must Break", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Perhaps", area_id: 26, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Deep End", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Hand Jive", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Kermit's Wad", area_id: 62, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Stop that Terrain", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Open Book", area_id: 14, protection_type: "Trad, Alpine", pitches: 5, picture: nil},
  {name: "Caress of Steel", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "cTr", area_id: 47, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Hook", area_id: 48, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Smitty's Wet Dream", area_id: 62, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Six to Eleven", area_id: 30, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Many Options", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rush Hour", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Battalion of Saints", area_id: 63, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Zesty", area_id: 45, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Leggo My Eggo", area_id: 64, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Callitwhatyouplease", area_id: 48, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Crescent Crack Direct Variation", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Melting Into Madness", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Schoolroom Direct Variation", area_id: 48, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Vertical Smile", area_id: 14, protection_type: "Trad, Alpine", pitches: 0, picture: nil},
  {name: "Touch of Teflon", area_id: 67, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Firstborn", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Chambered Nautilus", area_id: 67, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Antidote", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Movie Variation", area_id: 48, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Equipment Overhang Right", area_id: 24, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Remote  Control", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "High Fructose Corn Syrup", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Fowl Play", area_id: 69, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Twist and Shout", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Steel Monkey", area_id: 22, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "The Atheist", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Up In a Flash", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Schoolroom West", area_id: 48, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Pebbles and Bambam", area_id: 37, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Madison Avenue", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dreamscape", area_id: 61, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Worthy Whoopsie", area_id: 67, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Quicklime Girl", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bong A Long", area_id: 72, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Primal Magic", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bringer of Light", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rockapella", area_id: 30, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Maudlin", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Salem's Lot", area_id: 68, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Hatchet Crack", area_id: 48, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Italian Arete", area_id: 68, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Pig Pen", area_id: 74, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Sweet Jane Variation", area_id: 37, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Coral Bells Arete", area_id: 67, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "The Fin Arete", area_id: 75, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Witchhunt", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "La Creme De Shorts", area_id: 18, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Minions of Chaos", area_id: 77, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Gotta Be Tall Or Else You'll Fall", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Jug for Joy", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stoic Calculus", area_id: 30, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Tarzan", area_id: 37, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Jam Crack Route", area_id: 78, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Day as Night", area_id: 79, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Narcolepsy", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Variety Delight", area_id: 64, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Les is More", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "A Modest Man from Mandrake", area_id: 80, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Drop Zone", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Goth Girls", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bourbon Street", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dead Drunk", area_id: 72, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Crack Face", area_id: 81, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Psychobabble", area_id: 82, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Winky and Waxman Go Bolting", area_id: 47, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Enter the Dragon", area_id: 83, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Layback Crack", area_id: 18, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "39", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Crack in the Woods", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Rat Bastards", area_id: 66, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Barefoot in Barbados", area_id: 33, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Boiler Maker", area_id: 72, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bong Bong Firecracker", area_id: 84, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Wrecking Ball", area_id: 47, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Route 66", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Physical Therapy", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Union Dues", area_id: 86, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Inner Light", area_id: 36, protection_type: "TR", pitches: 1, picture: nil},
  {name: "Stem the Tide", area_id: 24, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Little Hellion", area_id: 55, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Melting Point", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Late for Dinner", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cranial Prophylactic", area_id: 62, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "MEGA", area_id: 67, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Flakes", area_id: 87, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Entre Nous", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Imperial", area_id: 58, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Climb and Punishment", area_id: 88, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Betty's Altered Elbow", area_id: 89, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Vixen Blonde (aka Punch the Clock)", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Minor Threat", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dog Pile", area_id: 59, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Vaporous Apparition", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Dorsal Fin", area_id: 75, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Endless Torment", area_id: 15, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Chug A Jug", area_id: 72, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Iraq in the Back Attack", area_id: 81, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "East Dihedrals", area_id: 29, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Teenagers in Heat", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "I Ran To Afghanistan", area_id: 81, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dry Socket", area_id: 91, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Nosferatu", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Lisa's Shoulder", area_id: 24, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Thieving Magpie", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Facial Fracture", area_id: 91, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Los Crudos", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Unknown 5.8", area_id: 72, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Conflict", area_id: 58, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Hoffa Finger", area_id: 86, protection_type: "Sport, TR", pitches: 0, picture: nil},
  {name: "Drunken Midget", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Moral Bells Arete", area_id: 67, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Errors of Our Ways", area_id: 81, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stump", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Left Pile", area_id: 59, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Groovin'", area_id: 64, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Geronimo", area_id: 92, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Beeline", area_id: 94, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Sweet and Low", area_id: 67, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Firefly", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Roll the Bones", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "I Think I'm Going Bald", area_id: 80, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Six Appeal", area_id: 18, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Riptide", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Japanese Terraces", area_id: 15, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Fall Equinox", area_id: 79, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Helix", area_id: 95, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dayglow Abortions", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Nuptial Vow", area_id: 96, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Out of Touch", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Red Light District", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Black Hole", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pocket Debris", area_id: 97, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Looney Tunes", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "The Edge of Chaos", area_id: 41, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Hellfire Variation", area_id: 36, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Pocket Change", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Fingertrip Variation", area_id: 37, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Chorus Line", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Fortress", area_id: 36, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "On the Skids", area_id: 80, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stone Ground", area_id: 98, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Errant Edge", area_id: 45, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Urban Sprawl", area_id: 92, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Gomer Pile", area_id: 59, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Blue Collar Crack", area_id: 45, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Six Pence", area_id: 18, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Clean Underwear", area_id: 92, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Confessional", area_id: 36, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Fuego", area_id: 99, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Standard Thumb", area_id: 13, protection_type: "Trad", pitches: 11, picture: nil},
  {name: "Skinny Len Crimps", area_id: 96, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Iron Curtain", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Mother of Pearl", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Take Me To The River", area_id: 80, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Gas Boost", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "40 oz to Freedom", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Public Nuisance", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Choir Boy", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Northwest Passage", area_id: 31, protection_type: "Trad, TR", pitches: 2, picture: nil},
  {name: "Browncoat", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Beckoning Call", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Steel Graffiti", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Total X", area_id: 36, protection_type: "Trad, Sport", pitches: 1, picture: nil},
  {name: "Mr. Sandman", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Shindig", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rightside Variation", area_id: 12, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Algorithm", area_id: 97, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "War Clamor", area_id: 81, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Burnt", area_id: 100, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Butterfingers", area_id: 22, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Brain Doner", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Monogamy", area_id: 96, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Trinity Right", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Deja Vu", area_id: 101, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Out of the Question", area_id: 4, protection_type: "Trad, Alpine", pitches: 3, picture: nil},
  {name: "Graffiti Patient", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Daily Diatribe", area_id: 67, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Mutation", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Devil's Advocate", area_id: 102, protection_type: "Sport, Alpine", pitches: 1, picture: nil},
  {name: "Reaching for Razors", area_id: 104, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Princess Di", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Flying Dutchman", area_id: 84, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Emotional Geometry", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Girls on Film", area_id: 106, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Shallow Beginning", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Big in Japan", area_id: 18, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Assembly Line", area_id: 86, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Middle Class Socialist Brat", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Sudden, Yet Inevitable Betrayal", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "If I Only Had a Brain", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Neopolitan", area_id: 109, protection_type: "Sport, TR", pitches: 0, picture: nil},
  {name: "The Abyss", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Bad Faith", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Blood Ruby", area_id: 111, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stormy Resurrection", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Pilled Out", area_id: 63, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Treehugger", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Flee Flicker", area_id: 113, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "3 Amigos", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Social Realism", area_id: 101, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Paranoia Streak", area_id: 62, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Depth of Field", area_id: 114, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Wisky Bench", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Starstruck", area_id: 115, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Neuromancer", area_id: 15, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bee Pitch, The", area_id: 69, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "The Flake", area_id: 18, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Geurt's Ridge", area_id: 116, protection_type: "Trad", pitches: 10, picture: nil},
  {name: "Corona", area_id: 117, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Electric Company", area_id: 118, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Beef Master", area_id: 63, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Boomerang", area_id: 49, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Up A Cliff Without a Ladder", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Hornets Nest", area_id: 117, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Weed Killer", area_id: 32, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Haven't A Clue", area_id: 80, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Hyperform", area_id: 119, protection_type: "Trad, Alpine", pitches: 4, picture: nil},
  {name: "Concrete Jungle", area_id: 99, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cool Your Jets", area_id: 120, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "To Air is Human", area_id: 87, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Utah Crack", area_id: 123, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Ravages Of Time", area_id: 78, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Anti Hero's", area_id: 106, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Erection or Ejection", area_id: 94, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Times Square", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Gordon's Linkup", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Lowe Blow", area_id: 64, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Psychostematic", area_id: 82, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Out to the Black", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Down, Dirty, Doublecrossed", area_id: 78, protection_type: "Trad", pitches: 5, picture: nil},
  {name: "MA   1", area_id: 26, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Indecent Exposure Variation", area_id: 13, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Bloody Impaction", area_id: 91, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Martinez Mind Melter", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Misery", area_id: 124, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Perestroika", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Drunk Punk Oi", area_id: 58, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Steel Reserve", area_id: 58, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "O'Doul's", area_id: 117, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Kiddie Pool", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Shotgun", area_id: 123, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Field of Screams", area_id: 118, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Goldenfingers", area_id: 125, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "The Kind", area_id: 126, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Step Right Up", area_id: 35, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pocket City", area_id: 127, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Transformer", area_id: 128, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Unknown 5.6", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Mind Blow", area_id: 48, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Coyne Crack", area_id: 13, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Lisa Falls Right", area_id: 113, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Gargoyle", area_id: 129, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Second East Face", area_id: 32, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Bubbles & Booze", area_id: 131, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Cuspidnator", area_id: 91, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "The Bird Is the Word", area_id: 66, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "The Hook Variation", area_id: 48, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rise and Revolt", area_id: 106, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Baghdad", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Code Blue", area_id: 132, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Purple Pumper", area_id: 131, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Merciless Onslaught", area_id: 118, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Involuntary Release", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Under the Knife", area_id: 132, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Skurge", area_id: 100, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Sam Adams", area_id: 117, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Double Tap", area_id: 68, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Fishlips", area_id: 36, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Tax Evasion", area_id: 88, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Fire and Brimstone", area_id: 36, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Horns Of Satan", area_id: 51, protection_type: "Trad, Alpine", pitches: 8, picture: nil},
  {name: "The Precious", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Encore", area_id: 18, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Unknown Left", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "No Recess", area_id: 133, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cough Your Off", area_id: 126, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Zombieland", area_id: 68, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Juggernaut Roof", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pick Pocket", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Crossing Over", area_id: 135, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Just Say No to Crack", area_id: 64, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pika Paradise", area_id: 4, protection_type: "Trad, Alpine", pitches: 2, picture: nil},
  {name: "Eternal Flow", area_id: 136, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Quicker Picker Upper", area_id: 30, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Megalopolis", area_id: 92, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "No Nuts", area_id: 137, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Disco Chicken", area_id: 33, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Burner", area_id: 138, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "No Remorse", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rock Requiem", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Chicken Wire", area_id: 139, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Hidden Agenda", area_id: 86, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dam Fine Cracks", area_id: 79, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Mission Impossible", area_id: 96, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Strong Arm With the Lads", area_id: 98, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Specter", area_id: 140, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Reasoning With The Unreasonable", area_id: 133, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Fleeting Glimpse", area_id: 113, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Dehumanized", area_id: 58, protection_type: "Trad, Sport", pitches: 1, picture: nil},
  {name: "Running Woman", area_id: 42, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Our Mrs. Reynolds", area_id: 141, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Born Again", area_id: 30, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Ignominious Demise", area_id: 86, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Losing My Religion ", area_id: 33, protection_type: "Trad", pitches: 3, picture: nil},
  {name: "Total Ramon", area_id: 58, protection_type: "Trad, Sport", pitches: 1, picture: nil},
  {name: "Hot  Pockets", area_id: 142, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cause for Alarm", area_id: 55, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Skyscraper", area_id: 92, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Grommet", area_id: 58, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Stuck a Flute in My", area_id: 40, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Eye in the Sky", area_id: 82, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Daddy Long Legs", area_id: 143, protection_type: "Trad, TR", pitches: 2, picture: nil},
  {name: "Woody Woodpecker", area_id: 133, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "This Must Be The Pickle", area_id: 94, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "God's WeedWacker", area_id: 133, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Repeat and Offend", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "If The Fall Doesnt Kill You A Car Will", area_id: 139, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Homecoming Princess", area_id: 145, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Undone Book", area_id: 14, protection_type: "Trad, Alpine", pitches: 5, picture: nil},
  {name: "Teardrop", area_id: 118, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "S-Crack", area_id: 13, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Malvado", area_id: 146, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Hell Raiser", area_id: 147, protection_type: "Trad", pitches: 5, picture: nil},
  {name: "The Answer", area_id: 4, protection_type: "Trad, Alpine", pitches: 3, picture: nil},
  {name: "Social Engineering", area_id: 29, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Too Young To Be Human", area_id: 149, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Flamin' Freddie", area_id: 47, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Shadow of the Blade", area_id: 51, protection_type: "Trad, Alpine", pitches: 7, picture: nil},
  {name: "Kamp's Ridge", area_id: 150, protection_type: "Trad", pitches: 8, picture: nil},
  {name: "Wilson-Love", area_id: 84, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Left Tributary", area_id: 31, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Weed B Gone", area_id: 32, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Maid In America", area_id: 86, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Ionic Bonding", area_id: 39, protection_type: "Sport", pitches: 2, picture: nil},
  {name: "Cosmic Imperative", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bushwhacked", area_id: 53, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Call Me Slim", area_id: 29, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Condor", area_id: 58, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Kermit's Direct Start", area_id: 62, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Angle of Repose", area_id: 98, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Karmic Whiplash", area_id: 151, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Rincon", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Can't Say", area_id: 57, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Blurred Vision", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Sin Nombre", area_id: 69, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Bottled Violence", area_id: 63, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Milkmaid", area_id: 73, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Way Hammered", area_id: 57, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Inside Information", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Sunset Arete", area_id: 153, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Get a Pump or Jump", area_id: 99, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Toxic Narcotic", area_id: 154, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Mandela", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Force of Nature", area_id: 29, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Certain Death", area_id: 33, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Pump It Until Purple", area_id: 131, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Total Recall", area_id: 42, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Motley Cruise", area_id: 71, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "\"That's What She Said'", area_id: 155, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Western Grebe", area_id: 157, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "Tuff Enough", area_id: 47, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Baked Bean Sandwich", area_id: 133, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Black Hash", area_id: 126, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Road Rage", area_id: 158, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Narcosis", area_id: 61, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Sinsemilla Crack", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Mad Swiller", area_id: 131, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Burning", area_id: 159, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Rusty Blade", area_id: 160, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Hogum's Heroes", area_id: 161, protection_type: "Trad, Alpine", pitches: 5, picture: nil},
  {name: "Junk Head", area_id: 106, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Butcher Knife", area_id: 10, protection_type: "Trad", pitches: 4, picture: nil},
  {name: "X", area_id: 163, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cotton Mouth King", area_id: 66, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Bad Case of Gingervitus ", area_id: 91, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Phantasmagorical", area_id: 145, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Death of a Sailsman", area_id: 94, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "The Lowe Route", area_id: 57, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Who's On First", area_id: 19, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Skid Row Variation", area_id: 39, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Body Bag", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Cross Town", area_id: 39, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Tingey's Direct", area_id: 37, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Hellgate Highway", area_id: 147, protection_type: "Sport", pitches: 4, picture: nil},
  {name: "Retro'd Hardman", area_id: 164, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Cross-Eyed and Painless", area_id: 80, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Awakening", area_id: 60, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "POLITRICS", area_id: 106, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "North Ridge", area_id: 166, protection_type: "Trad, Snow, Alpine", pitches: 0, picture: nil},
  {name: "Dumb Broads", area_id: 124, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Trench Warfare", area_id: 167, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Intensive Care", area_id: 168, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Holy Grail", area_id: 36, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "White Collar Redneck", area_id: 86, protection_type: "Sport, TR", pitches: 1, picture: nil},
  {name: "Rivers Edge", area_id: 172, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Black Magic", area_id: 95, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Double Standard", area_id: 173, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Steel Wheels", area_id: 174, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Little Creatures", area_id: 80, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Stifflers Stiffy", area_id: 40, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Comfort Zone", area_id: 33, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Face Plant", area_id: 91, protection_type: "Trad", pitches: 0, picture: nil},
  {name: "Devils Advocate on Crack", area_id: 102, protection_type: "Sport, Alpine", pitches: 1, picture: nil},
  {name: "Mission Control", area_id: 118, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Fallen Arches", area_id: 26, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Step into the Fire", area_id: 127, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Heisenberg", area_id: 175, protection_type: "Trad, Sport", pitches: 1, picture: nil},
  {name: "Piston Bully", area_id: 177, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Sudden Exposure", area_id: 139, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Gimme Danger", area_id: 83, protection_type: "Trad", pitches: 2, picture: nil},
  {name: "Riot In The City", area_id: 106, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Orogeny", area_id: 95, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Lord of the Long Arms", area_id: 31, protection_type: "Trad, TR", pitches: 1, picture: nil},
  {name: "Between The Lines", area_id: 22, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Ring That Bell", area_id: 178, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Edge of the Sea", area_id: 179, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Pearls Before Swine", area_id: 15, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Pocket Pumper", area_id: 127, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Shiny", area_id: 180, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Syllogism", area_id: 149, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Underdog", area_id: 118, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Melting", area_id: 159, protection_type: "Sport", pitches: 1, picture: nil},
  {name: "Baby Teeth", area_id: 91, protection_type: "Sport", pitches: 0, picture: nil},
  {name: "Fire Starter", area_id: 138, protection_type: "Trad", pitches: 1, picture: nil},
  {name: "Short Corner", area_id: 19, protection_type: "Trad", pitches: 1, picture: nil}
])
